server:
  port: 8080
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  file: ag_process
  path: /var/log

ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 3000

zuul:
  retryable: true
  routes:
    service:
      path: /service/**
      url: ribbon-service
    mbs-app:
      path: /mbs-app/**
      url: ribbon-mbs-app
    mbs-cms:
      path: /mbs-cms/**
      url: ribbon-mbs-cms
    mbs-dbs:
      path: /mbs-dbs/**
      url: ribbon-mbs-dbs

ribbon-service:
  ribbon:
    listOfServers: localhost:8011,localhost:8012,localhost:8021,localhost:8022,localhost:8031,localhost:8032
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon-mbs-app:
  ribbon:
    listOfServers: localhost:8011,localhost:8012
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon-mbs-cms:
  ribbon:
    listOfServers: localhost:8021,localhost:8022
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon-mbs-dbs:
  ribbon:
    listOfServers: localhost:8031,localhost:8032
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon-service-00:
  ribbon:
    listOfServers: 172.31.30.1:8888
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon-service-04:
  ribbon:
    listOfServers: localhost:8041,localhost:8042
    ServerListRefreshInterval: 15000
    ConnectTimeout: 1000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100